### PR TITLE
Feature/noe reactsecond

### PR DESCRIPTION
**Pull request by Rightnoe**

### CODE REVIEW

**Review by clementprdhomme — CHANGES_REQUESTED** [review]
Hi Noelia!

I've made some changes to your branch:
- I removed a purple image that you added and didn't use.
- I removed all the CSS prefixes. We use autoprefixer so you don't need to do it.
- I replaced the inline base64 reactions with external files as we could reuse it for other parts of the project.

The CSS you've written (everything that's inside `.c-reactions`) is not used. Could you bind it to where it's appropriate?

Also, the page still don't look right (might be because you didn't attach the CSS):
Post where the reactions don't have the right look

One issue you'll face is that you've put the reaction faces as background images but this won't work because you need to add colours behind them: https://projects.invisionapp.com/d/main#/console/12620160/264590648/preview

You can maybe check how I've did it for the reaction within the cards: https://github.com/Vizzuality/internet-health-report/blob/feature/noe-reactsecond/src/scss/components/c-reactions-icon.scss

I make a `<div>` round and give it a background colour. The reaction is placed on top of that.

**Comment by clementprdhomme** [comment]
I forgot! As I rebased the branch on `develop`, you need to run the following commands to delete it locally from your computer and re-download it:
```bash
git checkout develop
git branch -D feature/noe-reactsecond
git fetch
git checkout feature/noe-reactsecond
```

**Comment by Rightnoe** [comment]
Hi Clément!

I replaced the reactions external files with the small one 100% size. 
I've hidden comments icon by request of Clara. In footer.php
We can delete c-reactions.scss file, it's not imported in style.scss
I don't have access to: https://projects.invisionapp.com/d/main#/console/12620160/264590648/preview

Stylesheet still needs some adjustments for hover and mobile.
Sorry for my english :)

Thanks!

**Comment by clementprdhomme** [comment]
It looks much better!

We still need the background colour to the reactions, but I'll merge this PR meanwhile.

**Pull request merged**
